// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ShadowAPI.Models;
using System;

namespace ShadowAPI.Migrations
{
    [DbContext(typeof(RunnerContext))]
    partial class RunnerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShadowAPI.Models.Alias", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("InfoID");

                    b.Property<bool>("IsPrimary");

                    b.Property<string>("StreetName");

                    b.HasKey("ID");

                    b.HasIndex("InfoID");

                    b.ToTable("Alias");
                });

            modelBuilder.Entity("ShadowAPI.Models.Info", b =>
                {
                    b.Property<long>("ID");

                    b.Property<string>("Background");

                    b.Property<string>("Description");

                    b.Property<string>("Ethnicity");

                    b.Property<string>("ImageURL");

                    b.Property<byte>("Metatype");

                    b.Property<string>("RealName");

                    b.Property<string>("Sex");

                    b.HasKey("ID");

                    b.ToTable("Runner");
                });

            modelBuilder.Entity("ShadowAPI.Models.Runner", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.HasKey("ID");

                    b.ToTable("Runner");
                });

            modelBuilder.Entity("ShadowAPI.Models.Alias", b =>
                {
                    b.HasOne("ShadowAPI.Models.Info")
                        .WithMany("Aliases")
                        .HasForeignKey("InfoID");
                });

            modelBuilder.Entity("ShadowAPI.Models.Info", b =>
                {
                    b.HasOne("ShadowAPI.Models.Runner", "Runner")
                        .WithOne("Info")
                        .HasForeignKey("ShadowAPI.Models.Info", "ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
