// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using ShadowAPI.Models;
using ShadowAPI.Models.Enums;
using System;

namespace ShadowAPI.Migrations
{
    [DbContext(typeof(RunnerContext))]
    [Migration("20170904111013_RunnerContactManyToMany")]
    partial class RunnerContactManyToMany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ShadowAPI.Models.AdeptPower", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AwakenedID");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("AwakenedID");

                    b.ToTable("AdeptPower");
                });

            modelBuilder.Entity("ShadowAPI.Models.Alias", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("InfoID");

                    b.Property<bool>("IsPrimary");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("InfoID");

                    b.ToTable("Alias");
                });

            modelBuilder.Entity("ShadowAPI.Models.Attributes", b =>
                {
                    b.Property<long>("ID");

                    b.Property<int>("Agility");

                    b.Property<int>("Body");

                    b.Property<int>("Charisma");

                    b.Property<int>("Edge");

                    b.Property<float>("Essence");

                    b.Property<int>("Intuition");

                    b.Property<int>("Logic");

                    b.Property<int>("Magic");

                    b.Property<int>("Reaction");

                    b.Property<int>("Resonance");

                    b.Property<int>("Strength");

                    b.Property<int>("Willpower");

                    b.HasKey("ID");

                    b.ToTable("Runner");
                });

            modelBuilder.Entity("ShadowAPI.Models.Awakened", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.HasKey("ID");

                    b.ToTable("Awakened");
                });

            modelBuilder.Entity("ShadowAPI.Models.Contact", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Connection");

                    b.Property<string>("Favor");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("ShadowAPI.Models.Economy", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CurrentFunds");

                    b.HasKey("ID");

                    b.ToTable("Economy");
                });

            modelBuilder.Entity("ShadowAPI.Models.FundTransaction", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("EconomyID");

                    b.Property<string>("Name");

                    b.Property<long?>("PreviousTransactionID");

                    b.Property<long>("Value");

                    b.HasKey("ID");

                    b.HasIndex("EconomyID");

                    b.HasIndex("PreviousTransactionID");

                    b.ToTable("FundTransaction");
                });

            modelBuilder.Entity("ShadowAPI.Models.Identification", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<long?>("RunnerID");

                    b.HasKey("ID");

                    b.HasIndex("RunnerID");

                    b.ToTable("Identification");
                });

            modelBuilder.Entity("ShadowAPI.Models.Info", b =>
                {
                    b.Property<long>("ID");

                    b.Property<string>("Background");

                    b.Property<string>("Description");

                    b.Property<string>("Ethnicity");

                    b.Property<string>("ImageURL");

                    b.Property<byte>("Metatype");

                    b.Property<string>("RealName");

                    b.Property<string>("Sex");

                    b.HasKey("ID");

                    b.ToTable("Runner");
                });

            modelBuilder.Entity("ShadowAPI.Models.License", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("IdentificationID");

                    b.Property<string>("Name");

                    b.Property<string>("Nothing");

                    b.HasKey("ID");

                    b.HasIndex("IdentificationID");

                    b.ToTable("License");
                });

            modelBuilder.Entity("ShadowAPI.Models.Metamagic", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AwakenedID");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("AwakenedID");

                    b.ToTable("Metamagic");
                });

            modelBuilder.Entity("ShadowAPI.Models.Quality", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("ContradictorID");

                    b.Property<int>("Cost");

                    b.Property<string>("Description");

                    b.Property<bool>("IsPositive");

                    b.Property<int>("Modifier");

                    b.Property<string>("Name");

                    b.Property<long?>("RunnerID");

                    b.HasKey("ID");

                    b.HasIndex("ContradictorID");

                    b.HasIndex("RunnerID");

                    b.ToTable("Quality");
                });

            modelBuilder.Entity("ShadowAPI.Models.Ritual", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AwakenedID");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("AwakenedID");

                    b.ToTable("Ritual");
                });

            modelBuilder.Entity("ShadowAPI.Models.Runner", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AwakenedID");

                    b.Property<string>("Belongings");

                    b.Property<long?>("EconomyID");

                    b.Property<int>("Lifestyle");

                    b.Property<long?>("PlayerID");

                    b.HasKey("ID");

                    b.HasIndex("AwakenedID")
                        .IsUnique()
                        .HasFilter("[AwakenedID] IS NOT NULL");

                    b.HasIndex("EconomyID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Runner");
                });

            modelBuilder.Entity("ShadowAPI.Models.RunnerContact", b =>
                {
                    b.Property<long>("RunnerID");

                    b.Property<long>("ContactID");

                    b.Property<long>("ID");

                    b.Property<int>("Loyalty");

                    b.HasKey("RunnerID", "ContactID");

                    b.HasIndex("ContactID");

                    b.ToTable("RunnerContact");
                });

            modelBuilder.Entity("ShadowAPI.Models.Skill", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ActiveType");

                    b.Property<byte>("Group");

                    b.Property<int?>("KnowledgeType");

                    b.Property<string>("Name");

                    b.Property<int>("Rating");

                    b.Property<long?>("RunnerID");

                    b.Property<byte>("Type");

                    b.HasKey("ID");

                    b.HasIndex("RunnerID");

                    b.ToTable("Skill");
                });

            modelBuilder.Entity("ShadowAPI.Models.SkillSpecialization", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<long?>("SkillID");

                    b.HasKey("ID");

                    b.HasIndex("SkillID");

                    b.ToTable("SkillSpecialization");
                });

            modelBuilder.Entity("ShadowAPI.Models.Spell", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AwakenedID");

                    b.Property<int>("Drain");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("AwakenedID");

                    b.ToTable("Spell");
                });

            modelBuilder.Entity("ShadowAPI.Models.User", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<bool>("IsCurrentlyPlayer");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ShadowAPI.Models.AdeptPower", b =>
                {
                    b.HasOne("ShadowAPI.Models.Awakened")
                        .WithMany("AdeptPowers")
                        .HasForeignKey("AwakenedID");
                });

            modelBuilder.Entity("ShadowAPI.Models.Alias", b =>
                {
                    b.HasOne("ShadowAPI.Models.Info")
                        .WithMany("Aliases")
                        .HasForeignKey("InfoID");
                });

            modelBuilder.Entity("ShadowAPI.Models.Attributes", b =>
                {
                    b.HasOne("ShadowAPI.Models.Runner", "Runner")
                        .WithOne("Attributes")
                        .HasForeignKey("ShadowAPI.Models.Attributes", "ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShadowAPI.Models.FundTransaction", b =>
                {
                    b.HasOne("ShadowAPI.Models.Economy")
                        .WithMany("History")
                        .HasForeignKey("EconomyID");

                    b.HasOne("ShadowAPI.Models.FundTransaction", "PreviousTransaction")
                        .WithMany()
                        .HasForeignKey("PreviousTransactionID");
                });

            modelBuilder.Entity("ShadowAPI.Models.Identification", b =>
                {
                    b.HasOne("ShadowAPI.Models.Runner")
                        .WithMany("Ids")
                        .HasForeignKey("RunnerID");
                });

            modelBuilder.Entity("ShadowAPI.Models.Info", b =>
                {
                    b.HasOne("ShadowAPI.Models.Runner", "Runner")
                        .WithOne("Info")
                        .HasForeignKey("ShadowAPI.Models.Info", "ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShadowAPI.Models.License", b =>
                {
                    b.HasOne("ShadowAPI.Models.Identification")
                        .WithMany("Licenses")
                        .HasForeignKey("IdentificationID");
                });

            modelBuilder.Entity("ShadowAPI.Models.Metamagic", b =>
                {
                    b.HasOne("ShadowAPI.Models.Awakened")
                        .WithMany("Metamagics")
                        .HasForeignKey("AwakenedID");
                });

            modelBuilder.Entity("ShadowAPI.Models.Quality", b =>
                {
                    b.HasOne("ShadowAPI.Models.Quality", "Contradictor")
                        .WithMany()
                        .HasForeignKey("ContradictorID");

                    b.HasOne("ShadowAPI.Models.Runner")
                        .WithMany("Qualities")
                        .HasForeignKey("RunnerID");
                });

            modelBuilder.Entity("ShadowAPI.Models.Ritual", b =>
                {
                    b.HasOne("ShadowAPI.Models.Awakened")
                        .WithMany("Rituals")
                        .HasForeignKey("AwakenedID");
                });

            modelBuilder.Entity("ShadowAPI.Models.Runner", b =>
                {
                    b.HasOne("ShadowAPI.Models.Awakened", "Awakened")
                        .WithOne("Runner")
                        .HasForeignKey("ShadowAPI.Models.Runner", "AwakenedID");

                    b.HasOne("ShadowAPI.Models.Economy", "Economy")
                        .WithMany()
                        .HasForeignKey("EconomyID");

                    b.HasOne("ShadowAPI.Models.User", "Player")
                        .WithMany("Runners")
                        .HasForeignKey("PlayerID");
                });

            modelBuilder.Entity("ShadowAPI.Models.RunnerContact", b =>
                {
                    b.HasOne("ShadowAPI.Models.Contact", "Contact")
                        .WithMany("Runners")
                        .HasForeignKey("ContactID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ShadowAPI.Models.Runner", "Runner")
                        .WithMany("Contacts")
                        .HasForeignKey("RunnerID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ShadowAPI.Models.Skill", b =>
                {
                    b.HasOne("ShadowAPI.Models.Runner")
                        .WithMany("Skills")
                        .HasForeignKey("RunnerID");
                });

            modelBuilder.Entity("ShadowAPI.Models.SkillSpecialization", b =>
                {
                    b.HasOne("ShadowAPI.Models.Skill", "Skill")
                        .WithMany("Specialization")
                        .HasForeignKey("SkillID");
                });

            modelBuilder.Entity("ShadowAPI.Models.Spell", b =>
                {
                    b.HasOne("ShadowAPI.Models.Awakened")
                        .WithMany("Spells")
                        .HasForeignKey("AwakenedID");
                });
#pragma warning restore 612, 618
        }
    }
}
